# üí° Exercice 3 - TU + Mocking

Ce dossier pr√©sente une solution pour l'Exercice 3 qui consiste √† g√©rer les erreurs dans une fonction de r√©cup√©ration de donn√©es `fetchData` et √† √©crire ses tests unitaires en simulant des appels API. 

## üéØ Description de la Solution

### Modifications Apport√©es √† `utils.ts`

1. **Gestion d'Erreur** :
   - La fonction `fetchData` a √©t√© modifi√©e pour inclure la gestion des erreurs.
   - L'utilisation de `try/catch` permet de capturer et de g√©rer les erreurs li√©es aux r√©ponses d'API et aux probl√®mes de r√©seau.
   - Les erreurs sont classifi√©es et trait√©es en fonction de leur `mockStatusCode` pour une gestion appropri√©e.

### Modifications Apport√©es √† `utils.test.ts`

2. **Tests Unitaires** :
   - Utilisation de `jest.fn()` pour simuler les appels API et tester diff√©rents sc√©narios.
   - Les tests couvrent :
     - La r√©ussite de la r√©cup√©ration des donn√©es.
     - L'√©chec d√ª √† une erreur de r√©seau.
     - L'√©chec d√ª √† une erreur de r√©ponse API.

## üí° Conseils Techniques

- **Mocking** : Pour tester les fonctions asynchrones comme `fetchData`, nous avons utilis√© les capacit√©s de mocking de Jest via `jest.fn()`. Cela nous permet d'isoler la fonction et de l'appeler avec des arguments sp√©cifiques pour simuler diff√©rents sc√©narios.

- **Gestion d'Erreur** : Toujours s√©parer les types d'erreurs (par exemple, erreur r√©seau vs erreur API) pour un traitement plus granulaire et une meilleure compr√©hension des √©checs potentiels.

## ‚úÖ Conclusion

Cette impl√©mentation illustre comment g√©rer les erreurs de mani√®re robuste dans un environnement asynchrone et comment √©crire des tests unitaires efficaces en utilisant le mocking.